name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest  # Use Windows environment

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Specify Python 3.12

      - name: Create and activate virtual environment
        run: |
          python -m venv .venv
          .venv\Scripts\activate  # Correct for Windows

      - name: Install dependencies
        run: |
          .venv\Scripts\python -m pip install --upgrade pip
          .venv\Scripts\pip install -r requirements.txt

      - name: Run tests
        run: |
          .venv\Scripts\python -m unittest discover tests  # Ensure your tests are in the 'tests' folder

      - name: Run Streamlit
        run: |
          .venv\Scripts\streamlit run dashboard/app.py  # Path to your Streamlit app
